version: '3'
services: 
  web:
    build: .
    ports:
      - "6000:3000"
    volumes:
      - /app/node_modules
      - .:/app

  tests:
    build: .
    volumes: 
       - /app/node_modules
       - .:/app
    command: ["npm", "run", "test"]

